### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by tuyy** [yeongyeoncho91/TWL#3]
* README.md 에 TWL repo issue 작성 방법 및 필요한 공유 내용을 추가해주세요.

**Comment by tuyy** [comment]
@yeongyeoncho91 
월말 or 월초에 지난 달 총 리뷰하고 이슈 close 할까요?

**Comment by yeongyeoncho91** [comment]
넹!

**Comment by yeongyeoncho91** [comment]
@tuyy 
README.me 작성 완료했습니다. 확인 부탁드립니다!
